apiVersion: v2
name: rentacar-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
image:
  repository: RentACar/rentacar
  tag: latest
postgresql:
  enabled: true
  postgresqlDatabase: DbRentCar
  postgresqlUsername: postgres
  postgresqlPassword: 1234
  servicePort: 5432
service:
  type: LoadBalancer
  port: 8080
