apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentacar-deployment
  labels:
    app: rentacar
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: rentacar
  template:
    metadata:
      labels:
        app: rentacar
    spec:
      containers:
      - name: rentacar
        image: RentACar/rentacar:latest 
        ports:
        - containerPort: 80 
        env:
        - name: postgresqlDatabase
          value: DbRentCar
        - name: postgresqlUsername
          value: postgres
        - name: postgresqlPassword
          valueFrom:
            secretKeyRef:
              name: Password  
              key: 1234
        - name: Host
          value: localhost 
        - name: Port
          value: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: rentacar-volume
          mountPath: /app/data

      volumes:
      - name: rentacar-volume
        persistentVolumeClaim:
          claimName: rentacar-pv-claim  
---
apiVersion: v1
kind: Service
metadata:
  name: rentacar-service
  labels:
    app: rentacar
spec:
  type: LoadBalancer
  ports:
  - port: 80  # External Port
    targetPort: 80  # Internal Port in the Pod
  selector:
    app: rentacar
